### ISSUE TITLE
Attitude in usevelocity

### ISSUE THREAD

**Issue by iceberg1369** [lewis5499/GINS-Navi#1]
Nice project!
I would like to know dows gnss velocity updates state attitude?

**Comment by lewis5499** [comment]
I hope this message finds you well.

We have not yet completed the section on the dual-antenna update. Specifically, we use the GNSS velocity as an additional measurement update for the Kalman filter.

Thank you again for your attention to this matter.

**Comment by iceberg1369** [comment]
most GNSS OEMS velocity measurements are more accurate than position. if RTK is not available and we have velocity by GNSS. in this case useVelocity can correct attitude erors? I don't mean dual antenna GPS.

**Comment by lewis5499** [comment]
I understand your point. I haven't implemented the functionality to update the velocity independently when GNSS position information is unavailable. 

However, you can try modifying the gnssupdate function to achieve this. In this function, I have simply constrained the usability of position and velocity information based on their standard deviations, which is similar to your requirement.

Since the GNSS results for the project are based on post-processing with RTKLIB, the GNSS results are in the format read by RTKPLOT (position, position std, velocity, velocity std, etc., as detailed in the RTKLIB manual). Therefore, the positioning result for each timestamp in the result file includes both position and velocity. Additionally, the loosely-coupled integration considers float and fixed solutions, except for invalid solutions, to be usable for Kalman filter measurement updates. Thus, you can choose to update only the GNSS velocity based on the solution type to meet your needs (when usegnssvel is selected).

**Comment by lewis5499** [comment]
The gnss velocity update in GNSS/INS ESKF model can exactly affect(or correct) the error-state "attitude". 
You can see the specific algorithm for details.
